### ISSUE TITLE
remove generated pykeyvi.[pyx, cpp] files from git and generate them on the fly during build

### ISSUE THREAD

**Issue by narekgharibyan** [cliqz-oss/keyvi#187]

**Comment by hendrikmuhs** [comment]
The reason why these files are checked in: I want people to be able to clone and try the project with minimum effort and dependencies. Removing those files (BTW, pyx, not pxd) would require them to install a 'build environment' in order to use it. That would take to long and they would quickly loose interest.

Therefore this is not an option at the moment.

**Comment by narekgharibyan** [comment]
Yes, I fully agree that this was necessary back then for quick start. But don't we solve this problem with shipped packages ?

Regarding to 'build environment' setup: the only requirement this adds, to have installed `autowrap` along with `msgpack-python` and other packages listed in `requirements.txt`.

What I wanna achieve is to have something like this in `setup.py`
```
import autowrap
if one of pxds/*.pxd or addons/*.pxd is modified:
     autowrap(...)
```

So we will not have any merge conflicts and will not need `autowrap.sh` anymore.
